package com.myspace.test_abort_wih;

import org.kie.api.runtime.process.WorkItem;
import org.kie.api.runtime.process.WorkItemHandler;
import org.kie.api.runtime.process.WorkItemManager;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ManualOperation implements WorkItemHandler {

    @Override
    public void executeWorkItem(WorkItem workItem, WorkItemManager manager) {
        System.out.println("EXECUTING WORK ITEM, CREATING A WAIT STATE BY NOT COMPLETING IT");
    }

    @Override
    public void abortWorkItem(WorkItem workItem, WorkItemManager manager) {
        System.out.println("ABORTING WORK ITEM");
        manager.abortWorkItem(workItem.getId());
    }



}