package com.myspace.test_abort_wih;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ManualOperation implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ManualOperation() {
    }




}